DROP TABLE CART;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;

-- TABLE 생성
CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    MNAME VARCHAR2(30)NOT NULL,
    MADDRESS VARCHAR2(30)NOT NULL,
    MTEL VARCHAR(30)NOT NULL,
    MEMAIL VARCHAR2(30)NOT NULL
);

CREATE TABLE PRODUCT(
    PCODE VARCHAR2(20) PRIMARY KEY,
    PNAME VARCHAR2(20),
    PRICE NUMBER(6) NOT NULL,
    STOCK NUMBER(6) NOT NULL
    
);

CREATE TABLE CART(
    CNO NUMBER(9) PRIMARY KEY,
    QTY NUMBER(6),
    COST NUMBER(6),
    MID VARCHAR2(30) REFERENCES MEMBER(MID) NOT NULL,
    PCODE VARCHAR2(20) REFERENCES PRODUCT(PCODE) NOT NULL
);

CREATE SEQUENCE CART_SEQ MAXVALUE 999  NOCACHE;
DROP SEQUENCE CART_SEQ;

CREATE TABLE ORDERS(
    ONO NUMBER(10) PRIMARY KEY,
    ONAME VARCHAR2(30),
    OADDR VARCHAR2(30),
    OTEL VARCHAR2(30),
    ODATE DATE DEFAULT SYSDATE,
    MID VARCHAR2(30) REFERENCES MEMBER(MID)NOT NULL
);

CREATE TABLE ORDER_DETAIL(
    ODNO NUMBER(2) PRIMARY KEY,
    ONO NUMBER(10) REFERENCES ORDERS(ONO),
    PCODE VARCHAR2(30) REFERENCES PRODUCT(PCODE),
    QTY NUMBER(2),
    COST NUMBER(6)
);
CREATE SEQUENCE ORDER_DETAIL_SEQ MAXVALUE 999 NOCYCLE NOCACHE;
DROP SEQUENCE ORDER_DETAIL_SEQ;

SELECT *FROM MEMBER;
SELECT *FROM PRODUCT;
SELECT *FROM CART;
SELECT *FROM ORDERS;
SELECT *FROM ORDER_DETAIL;

-- INSERT MEMBER 
INSERT INTO MEMBER VALUES ('ABC','홍길동','서울시 관악구 신림동', '01099999999','HONG@HONG.COM');
INSERT INTO MEMBER VALUES ('DEF','김김동','경기도 수원시', '01088888888','KIM@KIM.COM');

SELECT *FROM MEMBER;
-- INSERT PRODUCT
INSERT INTO PRODUCT VALUES ('A1', '맥주', 3000, 100);
INSERT INTO PRODUCT VALUES ('A2', '마스크', 200, 100);
INSERT INTO PRODUCT VALUES ('B1', '땅콩', 3000, 100);
INSERT INTO PRODUCT VALUES ('B2', '오징어', 5000, 100);
INSERT INTO PRODUCT VALUES ('C1', '소독약', 7000, 100);

SELECT *FROM PRODUCT;

-- INSERT ORDERS