-- 테이블 제거
DROP TABLE MEMBER CASCADE CONSTRAINTS;

-- 테이블 생성
CREATE TABLE MEMBER(
    ID VARCHAR2 (30),
    PW VARCHAR2 (30) NOT NULL,
    NAME VARCHAR2 (30) NOT NULL,
    BIRTH DATE,
    RDATE DATE DEFAULT SYSDATE NOT NULL, --등록시점
    PRIMARY KEY(ID)
);

-- 더미 데이터
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES('AAA','111','홍길동','99/12/12');
INSERT INTO MEMBER (ID, PW, NAME, BIRTH, RDATE)
    VALUES('BBB','222','김길동','01/12/12','24/01/01');
SELECT * FROM MEMBER;

--DAO에 들어갈 QUERY
-- PUBLIC INT INSERMEMBER(MEMBER NEW MEMBER)
INSERT INTO MEMBER (ID, PW, NAME, BIRTH)
    VALUES('CCC','111','홍길동',TO_DATE('2001-01-01','YYYY-MM-DD'));

-- PUBLIC MEMBER GETCOUNTMEMBER (String id)
SELECT COUNT(*) FROM MEMBER WHERE ID='AAA';
-- public arraylist <member>   getMemberList(몇등, 몇등);
SELECT * FROM MEMBER ORDER BY NAME;
COMMIT;
